/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'agri-bg': '#0a0f1e',
        'agri-bg-soft': '#0f1628',
        'agri-card': '#0d1721',
        'agri-card-elevated': '#111d2d',
        'agri-mint': '#00ff88',
        'agri-mint-dim': '#00cc6a',
        'agri-text-muted': '#8ba3b0',
        'primary': '#00ff88',
        'surface': '#0b1326',
        'on-surface': '#dae2fd',
        'surface-container': '#171f33',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-container-lowest': '#060e20',
        'on-surface-variant': '#bbcabf',
        'outline-variant': '#3c4a42',
        'secondary-container': '#0b513d',
        'on-secondary-container': '#83c2a9',
        'primary-container': '#10b981',
        'on-primary': '#050a0f',
        'on-primary-container': '#00422b',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#00cc7e',
        'secondary': '#95d3ba',
        'on-secondary': '#003829',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'outline': '#86948a',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'tertiary': '#ffb3af',
        'tertiary-container': '#fc7c78',
        'on-tertiary': '#650911',
        'inverse-primary': '#006c49',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
